### PR TITLE
Crosslinks store start and end epoch

### PR DESCRIPTION
**Pull request by vbuterin**
Solves #1034

### CODE REVIEW

**Comment by vbuterin** [comment]
Looks like this one requires substantial revision to tests :smile:

**Comment by hwwhww** [comment]
@vbuterin you forgot to update `1_custody-game.md` file. 😄

**Comment by djrtwo** [comment]
I'll take care of the tests as I review

**Comment by djrtwo** [comment]
Fixed and added some tests. Looks good to me other than the phase 1 update

**Pull request merged**
