### PR TITLE
Change if statements in get_crosslink_committes

### LINKED ISSUE #639: get_crosslink_committees reads previous_seed during genesis_epoch
### Summary

During `GENESIS_EPOCH`, `get_crosslink_committees_at_slot(..)` reads `state.previous_shuffling_epoch` when `epoch == current_epoch`.

### Detail

`get_crosslink_committees_at_slot(...)` first checks for `epoch == previous_epoch`, then checks for `epoch == current_epoch`.

During the genesis epoch, `current_epoch == previous_epoch` and the function so uses `state.previous_shuffling_epoch == ZERO_HASH` for shuffling.

During the next epoch (`GENESIS_EPOCH + 1`), when you wish to get the shuffling for `GENESIS_EPOCH`, you also trigger the `current_epoch == previous_epoch` path. However, `state.previous_shuffling_epoch != ZERO_HASH` anymore -- it is now the value that was set during `get_genesis_beacon_state(...)` (a.k.a. `current_shuffling_seed` during `GENESIS_EPOCH`).

## Proposed Solutions

1. (Preferred) Swap the `if` statements for so we first check for `epoch == current_epoch`, then `epoch == previous_epoch`.
2. (Seems wrong) During `get_genesis_beacon_state(..)`  ensure `state.previous_shuffling_seed` is also set to `generate_seed(state, GENESIS_EPOCH)`.

### PR DESCRIPTION
**Pull request by paulhauner**
Fixes #639.

### CODE REVIEW

**Comment by JustinDrake** [comment]
Why doesn't `get_previous_epoch(state)` always return `get_current_epoch(state) - 1`?

**Comment by djrtwo** [comment]
^ remnant from when we started epoch at 0.
We should not resolve #626 before we modify `get_previous_epoch`. Seems like people want to see epochs/slots to start at 0

**Comment by JustinDrake** [comment]
I see three ways to prevent underflows:

1) Add a bunch of subtle and crufty `if` special cases across the codebase. We already tried this and In hindsight it feels like the wrong way forward.
2) As suggested in #626, use `int64` (as opposed to `uint64`) for `slot` and `epoch` and start with `GENESIS_SLOT = 0`. Definitely better than 1) but maybe not quite as clean as 2).
3) Have `GENESIS_SLOT` be large enough. It was my mistake to not realise that `2**63` would cause complications with Java and it's unfortunate there's no obvious choice. My latest proposal is `2**n * SECONDS_PER_DAY/SECONDS_PER_SLOT` where `n` is the smallest sufficiently large exponent.

**Comment by djrtwo** [comment]
@paulhauner #655 addresses this immediate issue. I'm combing the spec to make sure that the initial previous epoch being before genesis_epoch doesn't open up any unexpected new bugs

**Pull request closed without merging**
