### PR TITLE
Fix #1262

### LINKED ISSUE #1262: Check attestation bit list length against committee size
In `get_attesting_indices`, we used to `verify_bitfield` to ensure the attestation bitfield length was the size the committee.
Now we've moved the verification of _a_ length to the ssz deserialization, but removed the committee size check.

### PR DESCRIPTION
**Pull request by JustinDrake**
Check length of (aggregation and custody) bits against the committee size.

Todo: Add tests

### CODE REVIEW

**Comment by JustinDrake** [comment]
>  djrtwo changed the base branch from `dev` to `v08x`

Is this a bug to fix in `v08x`? My assumption was that, for the duration of the freeze, we would only push non-substantive changes as well as bugs that prevent the proper formation of cross-client testnets. This bug arguably does not impede cross-client testnets.

**Comment by JustinDrake** [comment]
> My inclination is to put the check in `process_attestation` and to check explicitly against both aggregation and custody bits

Yes, that is clearer :)

**Comment by djrtwo** [comment]
cleaning this up

**Comment by dankrad** [comment]
> My inclination is to put the check in `process_attestation` and to check explicitly against both aggregation and custody bits.

Just independently came across this and put this fix in #1305  in `process_attestation`. Should we move the implementation here: https://github.com/ethereum/eth2.0-specs/pull/1305/files#diff-51a43328a58414e132a744f3771f018c

**Comment by djrtwo** [comment]
yes, That's where the fix should go. Have a separate PR with tests coming

**Comment by djrtwo** [comment]
close in favor of #1317

**Pull request closed without merging**
