### PR TITLE
Explicit assert when accessing state.validators out of bounds

### PR DESCRIPTION
**Pull request by JustinDrake**
Address most of #1091.

### CODE REVIEW

**Comment by protolambda** [comment]
Although I do fully support the idea of checking inputs for fuzzing, this PR takes it too extreme:
- IndexError should be like a panic. Not an Assertion. This defeats the whole purpose of input checking. We want to check inputs where we think they are untrusted. Then catch unexpected errors with fuzzing, like Go panics, (IndexError here).
- This pollutes the epoch-processing execution path with asserts. We don't have, or need, any asserts for trusted data.
- This unfortunately breaks a few readability things (typing becomes stronger in a few places, but I dislike changing that in the spec just before freeze)

I propose we introduce `check_index` function which maps an `int` to a `ValidatorIndex`, asserting it is within range, and only apply it on untrusted block inputs. A presentation thing, for after freeze.

**Comment by JustinDrake** [comment]
> IndexError should be like a panic. Not an Assertion.

Disagree for user-inputs which are not trusted.

**Comment by protolambda** [comment]
You're misunderstanding me there. Untrusted inputs can be checked with an assertion instead. This will make those invalid lookups throw an assertion, as part of the regular assertion based validation. Then IndexError can then start to be regarded as a panic, something that only occurs when logic or assumptions are wrong. We can then catch those cases, and separately so from the noise created by correct (i.e. reject block because this/that) assertion errors during fuzzing.
This would effectively require only a check function (or getter with assertion) in a select few spots where we parse validator indices from untrusted block inputs.

**Comment by JustinDrake** [comment]
> in a select few spots 

So I tried going that route to start with and there's a bunch of spots. Don't care too much either way.

**Pull request closed without merging**
