### PR TITLE
Ensure order-of-operations for shuffling shard mod

### PR DESCRIPTION
**Pull request by paulhauner**
## What

Add some brackets to `update_registry_and_shuffling_data` to ensure `shuffling_start_shard < SHARD_COUNT`.

## Why

The following [code](http://www.pythonsandbox.com/code/pythonsandbox_u169_03GfTXHz6XSp7Vtx1XN07cqd_v0.py) runs and prints "end"

```python
epoch_committee_count = 2047;
SHARD_COUNT = 1024;
old_shuffling_start = 1023;

current_shuffling_start_shard = (
	old_shuffling_start +
	epoch_committee_count % SHARD_COUNT
)

assert(current_shuffling_start_shard > SHARD_COUNT)

current_shuffling_start_shard = (
	(old_shuffling_start +
	epoch_committee_count) % SHARD_COUNT
)

assert(current_shuffling_start_shard < SHARD_COUNT)

print("end")
```

### CODE REVIEW

**Comment by JustinDrake** [comment]
This bug fix was subsumed in #808

**Comment by JustinDrake** [comment]
Can we get rid of `state.validator_registry_update_epoch` and rely on just `state.finalized_epoch`?

The simplifications are 🤯. Loving it!

**Comment by djrtwo** [comment]
Actually going to express this to master for v0.5.1

**Comment by djrtwo** [comment]
closing in favor of #821

**Pull request closed without merging**
