### PR TITLE
Use hash_tree_root everywhere

### PR DESCRIPTION
**Pull request by JustinDrake**
And get rid of merkle_root. This is possible because of SSZ tuples.

### CODE REVIEW

**Comment by vbuterin** [comment]
I don't see how this can be valid python. `hash_tree_root` for non-SSZ-containers doesn't distinguish between fixed size and variable size lists, but the spec does. Maybe add an optional `typ` argument to `hash_tree_root` ?

**Comment by JustinDrake** [comment]
I defined a new SSZ object :)

**Comment by djrtwo** [comment]
I'll make sure this runs in the executable spec before merging

**Comment by djrtwo** [comment]
lol found a couple of other bugs when running the state transition through many empty epochs! patching a fix in another PR

**Pull request merged**
