### PR TITLE
Deposits: define `DepositData` and rename `DepositParameters` to `DepositInput`

### PR DESCRIPTION
**Pull request by hwwhww**
1. Add `DepositData`.
2. Fix `get_initial_beacon_state` a tiny bug by adding a comma.
3. **Rename** `DepositParameters` to `DepositInput`.

### CODE REVIEW

**Comment by JustinDrake** [comment]
On second thought, is there a good reason for not merging `DepositData` and `DepositInput` into a single flat object? cc @djrtwo

**Comment by djrtwo** [comment]
It is marginally beneficial that the log outputs `deposit_data` as a a properly formatted SSZ object corresponding to `DepositData`.  This is done primarily through requiring the input to be an SSZ object itself `DepositInput` and then concatenating it with the additional time and deposit gwei value fields.

This is nice because the deposit contract doesn't need to a priori know anything about the required input fields which could allow us to change them down the line without deploying a new pow deposit contract.

**Comment by djrtwo** [comment]
You could flatten the object, but the depositor would need to know that they need to remove two fields from the specified SSZ  object. 

With the separate objects, it is clearer how to construct the deposit input data

**Comment by JustinDrake** [comment]
> With the separate objects, it is clearer how to construct the deposit input data

Makes sense. Next question: Can `Deposit` and `DepositData` be flattened? That is, we define `Deposit` to be

```
{
    'merkle_branch': '[hash32]',
    'merkle_tree_index': 'uint64',
    'value': 'uint64',
    'timestamp': 'uint64',
    'deposit_input': DepositInput,
}
```

**Pull request merged**
