### PR TITLE
Increase proposer rewards

### PR DESCRIPTION
**Pull request by JustinDrake**
Replacement for #735.

### CODE REVIEW

**Comment by djrtwo** [comment]
why not the proportional balance portion of this PR?

**Comment by JustinDrake** [comment]
> why not the proportional balance portion of this PR?

Because of https://github.com/ethereum/eth2.0-specs/pull/772

**Comment by djrtwo** [comment]
Comment from @vbuterin  on the other thread

> Not building on the head is very risky in the current setup because the head would dominate with many attestations very quickly, but I definitely see the rationale in not encouraging trying.

> BTW the need for this patch is arguably removed by the fair proposer selection patch. So if we feel the 1/8 reward is enough we could just close this?

**Comment by djrtwo** [comment]
I believe there was rough consensus to close this?

**Comment by JustinDrake** [comment]
I guess we can review this with the other economic constants.

**Pull request closed without merging**
