### PR TITLE
WIP: Port Solidity deposit contract

### PR DESCRIPTION
**Pull request by hwwhww**
Address #1968 

TODOs
- [x] Port the whole repo with commit history
- [x] Integrate the dapp.tools tests with CI
- [ ] Relicense Apache-2.0 to ???
- [ ] Clean up the configuration and add the web3.py tester back to the CI
- [ ] Clean up the documents

### CODE REVIEW

**Comment by djrtwo** [comment]
@hwwhww are there any blockers here? We should try to get this out in a release asap

**Comment by hwwhww** [comment]
@djrtwo 
waiting for merging https://github.com/axic/eth2-deposit-contract/pull/38 🙏

**Comment by axic** [comment]
Apologies for the delays, merged everything "upstream".  And tagged it `r2`: https://github.com/axic/eth2-deposit-contract/pull/38#issuecomment-673695943

**Comment by hwwhww** [comment]
replaced by #2019

**Pull request closed without merging**
