### PR TITLE
v1.0 release

### PR DESCRIPTION
**Pull request by djrtwo**
- [x] add `MIN_GENESIS_TIME`
- [x] add `DEPOSIT_CONTRACT_ADDRESS`
- [x] other mainnet config param updates (reduce punitiveness -- see https://github.com/ethereum/EIPs/pull/2982 for discussion, and make eth1data voting more conservative)
- [x] BLSv4 [#2080]
- [x] discv5.1
- [x] Gossipsub v1.1 scoring params [note added about them still coming]
- [x] additional genesis initialization tests [#2083]

### CODE REVIEW

**Review by melyalex — APPROVED** [review]

**Review by melyalex — APPROVED** [review]

**Review by JustinDrake — APPROVED** [review]
🎉

**Review by benjaminion — APPROVED** [review]
LGTM 🚀  (On behalf of the Teku crew)

**Review by CarlBeek — APPROVED** [review]
Looks good to me!

**Review by protolambda — APPROVED** [review]
Ready for launch

Edit: for those watching, we are updating some notes here and there to better reflect mainnet.

**Comment by ymonye** [comment]
greg_riba_bet_more.gif

**Comment by terencechain** [comment]
LGTM (On behalf of the Prysm crew)

**Comment by protolambda** [comment]
Moderation comment: feedback welcome, but keep meme comments for the after party, not the final straws

**Review by wemeetagain — APPROVED** [review]
:+1::rocket:  on behalf of the Lodestar team

**Comment by fabiotongson** [comment]
Awesome work 🚀🚀🚀

**Comment by MStevenZheng** [comment]
Here for the future screenshots

**Comment by Akif-G** [comment]
Great Job!

**Comment by paulmillr** [comment]
Hell yeah.

**Comment by leontodd** [comment]
LGTM on behalf of me

**Comment by AlexMasmej** [comment]
History made :)

**Comment by rune20** [comment]
Here for the historical moment! LFG!

**Comment by pinkhoodie** [comment]
This is incredible. Congrats everyone 🥳

**Comment by captainheart** [comment]
Incredible! Hurray! 👍🏻

**Comment by BenjellounO** [comment]
Well done everyone!! such an incredible milestone achieved right here and  High 5 to all of the engineers and researchers who have worked on this release.

**Comment by Blackskar875** [comment]
import asyncio
import os
import sys


# For not importing staking_deposit here
DEFAULT_VALIDATOR_KEYS_FOLDER_NAME = 'validator_keys'


async def main(argv):
    binary_file_path = argv[1]
    my_folder_path = os.path.join(os.getcwd(), 'TESTING_TEMP_FOLDER')
    if not os.path.exists(my_folder_path):
        os.mkdir(my_folder_path)

    if os.name == 'nt':  # Windows
        run_script_cmd = ".\\" + binary_file_path + '\deposit.exe'
    else:  # Mac or Linux
        run_script_cmd = './' + binary_file_path + '/deposit'

    cmd_args = [
        run_script_cmd,
        '--language', 'english',
        '--non_interactive',
        'new-mnemonic',
        '--num_validators', '1',
        '--mnemonic_language', 'english',
        '--chain', 'mainnet',
        '--keystore_password', 'MyPassword',
        '--folder', my_folder_path,
    ]
    proc = await asyncio.create_subprocess_shell(
        ' '.join(cmd_args),
        stdin=asyncio.subprocess.PIPE,
        stdout=asyncio.subprocess.PIPE,
        stderr=asyncio.subprocess.PIPE,
    )
    seed_phrase = ''
    parsing = False
    async for out in proc.stdout:
        output = out.decode('utf-8').rstrip()
        if output.startswith("This is your mnemonic"):
            parsing = True
        elif output.startswith("Please type your mnemonic"):
            parsing = False
        elif parsing:
            seed_phrase += output
            if len(seed_phrase) > 0:
                encoded_phrase = seed_phrase.encode()
                proc.stdin.write(encoded_phrase)

**Pull request merged**
