### PR TITLE
Remove version number in file name

### PR DESCRIPTION
**Pull request by JustinDrake**
Putting the version number in the file name is not future proof

### CODE REVIEW

**Comment by hwwhww** [comment]
I think there will be more documents in `/specs` beside this one, so might more friendly to have a title in the file name. And it will be excellent if we can guarantee no more v2.2, v3. (fingers crossed)

**Comment by JustinDrake** [comment]
We could remove version numbers altogether. It's a bit confusing to have "Ethereum 2.0" and "Spec version 2.1".

**Comment by djrtwo** [comment]
What about `beacon-chain.md`?

I think it best to not just be "spec" in the context of what will be a bunch of spec docs. It will also imply that we should put the shard chains spec in another doc.

Will also start updating the readme to link to various docs

**Comment by JustinDrake** [comment]
A separate doc for the shards makes sense

**Comment by djrtwo** [comment]
handling merge conflict then merging

**Pull request merged**
