### PR TITLE
Increase length of historical vectors

### PR DESCRIPTION
**Pull request by JustinDrake**
Address item 11 of #1054. This stores 8-month old historical start shards so that historical committees to be recomputed (e.g. for attester slashings).

Notice this makes slashing quite harsh:

> state.validator_registry[slashed_index].withdrawable_epoch = current_epoch + EPOCHS_PER_HISTORICAL_VECTOR

### CODE REVIEW

**Comment by djrtwo** [comment]
Two options to reduce slashing severity

* Just use a different vector length for the slashing accumulation array
* Do not use the entire array of history for calculating the total slashed in the period.  Can make `total_at_start` be something like the following `total_at_start = state.latest_slashed_balances[(current_epoch + EPOCHS_PER_HISTORICAL_VECTOR - EPOCHS_PER_SLASHING_PERIOD) % EPOCHS_PER_HISTORICAL_VECTOR]`

**Comment by vbuterin** [comment]
Agree that we don't need to make slashing lead to an 8 month delay; probably best to keep the current ~36 days.

**Comment by djrtwo** [comment]
@JustinDrake What route do you want to go here?

**Comment by JustinDrake** [comment]
> What route do you want to go here?

"Just use a different vector length for the slashing accumulation array" sounds fine :) (I'm at a zkSNARKs workshop this week—do you mind going ahead on this one?)

**Comment by djrtwo** [comment]
on it

**Comment by djrtwo** [comment]
closing in favor of #1196

**Pull request closed without merging**
