### PR TITLE
Reorg tests and add finality test suite

### PR DESCRIPTION
**Pull request by hwwhww**
1. Reorg the directories a bit.
    - Now all the tests cases are under `pyspec/eth2spec/test/phase0` or `pyspec/eth2spec/test/phase1`:
    - All the unittests (non-client-test-vectors) are under `pyspec/eth2spec/test/phase0/unittests` or  `pyspec/eth2spec/test/phase1/unittests`

```
├── phase0
│   ├── __init__.py
│   ├── block_processing
│   │   ├── __init__.py
│   │   ├── test_process_attestation.py
│   │   ├── test_process_attester_slashing.py
│   │   ├── test_process_block_header.py
│   │   ├── test_process_deposit.py
│   │   ├── test_process_proposer_slashing.py
│   │   └── test_process_voluntary_exit.py
│   ├── epoch_processing
│   │   ├── __init__.py
│   │   ├── run_epoch_process_base.py
│   │   ├── test_process_final_updates.py
│   │   ├── test_process_justification_and_finalization.py
│   │   ├── test_process_registry_updates.py
│   │   ├── test_process_rewards_and_penalties.py
│   │   └── test_process_slashings.py
│   ├── finality
│   │   ├── __init__.py
│   │   └── test_finality.py
│   ├── genesis
│   │   ├── __init__.py
│   │   ├── test_initialization.py
│   │   └── test_validity.py
│   ├── rewards
│   │   ├── __init__.py
│   │   ├── test_basic.py
│   │   ├── test_leak.py
│   │   └── test_random.py
│   ├── sanity
│   │   ├── __init__.py
│   │   ├── test_blocks.py
│   │   └── test_slots.py
│   └── unittests
│       ├── fork_choice
│       │   ├── test_get_head.py
│       │   ├── test_on_attestation.py
│       │   ├── test_on_block.py
│       │   └── test_on_tick.py
│       └── validator
│           └── test_validator_unittest.py
├── phase1
│   ├── __init__.py
│   ├── block_processing
│   │   ├── __init__.py
│   │   ├── test_process_attestation.py
│   │   ├── test_process_chunk_challenge.py
│   │   ├── test_process_custody_key_reveal.py
│   │   ├── test_process_custody_slashing.py
│   │   ├── test_process_early_derived_secret_reveal.py
│   │   └── test_process_shard_transition.py
│   ├── epoch_processing
│   │   ├── __init__.py
│   │   ├── test_process_challenge_deadlines.py
│   │   ├── test_process_custody_final_updates.py
│   │   └── test_process_reveal_deadlines.py
│   ├── sanity
│   │   ├── __init__.py
│   │   ├── test_blocks.py
│   │   └── test_shard_blocks.py
│   └── unittests
│       ├── __init__.py
│       ├── fork_choice
│       │   └── test_on_shard_head.py
│       └── test_get_start_shard.py

```

2. Add finality test generator: use the same format as `sanity/blocks`.

### CODE REVIEW

**Comment by hwwhww** [comment]
@protolambda

> In the tree-view you posted there are a few directories without an __init__.py, can you add where missing please? Or are those few cases intentional?

Kinda intentional for `unittests`. I suppose only the tests that invoked by test generators need `__init__.py`? I didn't add `__init__.py`  for `unittests`, but I can add if you think it's better. :)

**Comment by protolambda** [comment]
For `unittests`, if it's not imported then it's fine. And thanks for checking `finality` package. Should be good now. I'll run the test generators and tests before merge to double check :+1:

**Comment by protolambda** [comment]
See https://github.com/ethereum/eth2.0-specs/pull/1993

I generated the full test suite, with BLS, and it passes in ZRNT, including new finality tests. For both mainnet and minimal config.

**Comment by djrtwo** [comment]
#1993 merged in. this looks ready to me

**Pull request merged**
