### PR TITLE
Split off fork choice rule and deposit contract

### PR DESCRIPTION
**Pull request by JustinDrake**
Move the beacon chain fork choice rule to `0_fork-choice.md`, and the section on the deposit contract to `0_deposit-contract.md`. The `0_beacon_chain.md` file is for the state transition function exclusively.

### CODE REVIEW

**Comment by hwwhww** [comment]
I like it! But we can wait after #917 is merged and re-split it again. :D

**Comment by hwwhww** [comment]
@JustinDrake oh I meant #936! #917 seems huge but no conflict to this PR.
Would you like to solve the conflicts? (I guess re-splitting the content is easier.)

**Comment by JustinDrake** [comment]
I'll re-split when the dust settles

**Comment by djrtwo** [comment]
Cleaned it up, fixed readme, and links

**Pull request merged**
