### PR TITLE
Vyper b13 -> b13.hotfix1761

### PR DESCRIPTION
**Pull request by daejunpark**
Update to Vyper hotfix release, as suggested in https://github.com/vyperlang/vyper/pull/1771#issuecomment-566791919

### CODE REVIEW

**Comment by djrtwo** [comment]
It seems like the build cache was keeping vyper at the hold version. Now the build is failing to setup the environment with the new vyper version. investigating

Can see failed build of test env with new vyper version here
https://app.circleci.com/jobs/github/ethereum/eth2.0-specs/11845

**Comment by djrtwo** [comment]
It appears that building using `pip` and github archive fails no matter which vyper archive I point it to. still poking around

**Comment by djrtwo** [comment]
I can't successfully get any of the vyper archives to build via `pip` and the `tar.gz`. Looks like they plan to release this hotfix to pypi, so will wait on that until I try again.

**Comment by djrtwo** [comment]
closing in favor of #1539

**Comment by daejunpark** [comment]
Thanks for fixing that!

**Pull request closed without merging**
