### PR TITLE
Simplify deposits

### LINKED ISSUE #760: Remove DepositData
Currently `DepositData` is:

```python
{
    # Amount in Gwei
    'amount': 'uint64',
    # Timestamp from deposit contract
    'timestamp': 'uint64',
    # Deposit input
    'deposit_input': DepositInput,
}
```

We already discussed removing `timestamp`. Further, we can put `amount` inside `DepositInput` because (unlike `timestamp`) it is known ahead of time and can be signed over by the `proof_of_possession`.

This would allow us to reduce to two objects for deposits: `Deposit` and `DepositInput`. (We could then rename `DepositInput` to `DepositData` for consistency.)

### PR DESCRIPTION
**Pull request by JustinDrake**
Fix #760

### CODE REVIEW

**Comment by JustinDrake** [comment]
Opened an issue :)

https://github.com/ethereum/deposit_contract/issues/24

**Comment by NIC619** [comment]
Opened the  PR at 
https://github.com/ethereum/deposit_contract/pull/25 .

I didn't change much: first compute `amount` from `msg.value` then concatenate it with `deposit_input`.
But this differs from the spec in the order of the data in `deposit_data`:
this PR has `amount + pubkey + withdrawal_credentials + proof_of_possession`,
spec has `pubkey + withdrawal_credentials + amount  + proof_of_possession`.
I can change the order if the spec one is preferred.

**Comment by JustinDrake** [comment]
@NIC619 The spec ordering was chosen to be consistent with the `Validator` object which has `pubkey` and `withdrawal_credentials` as the first two fields (those are the two fixed fields).

**Comment by NIC619** [comment]
@JustinDrake Updated in 
https://github.com/ethereum/deposit_contract/pull/25/commits/4c8ad52cb2ef6f86864e9ef862b7f3652352c8d8

**Comment by djrtwo** [comment]
Similar to #779 , @NIC619 I think we should merge https://github.com/ethereum/deposit_contract/pull/25 into `dev` only to be released when this is released via v0.6.0 as to not confuse those targeting v0.5.x

**Pull request merged**
