### PR TITLE
RST/Sphinx docs

### PR DESCRIPTION
**Pull request by hwwhww**
Per discussion on #412 and #793, here's a branch to see the what would a Sphinx doc be: https://github.com/hwwhww/eth2.0-specs/tree/hwwhww/sphinx

(copied the docs setting from [ethereum-python-project-template](https://github.com/ethereum/ethereum-python-project-template).)

### Modulization
This PR includes some meta updates
1.  The `/eth2_specs` dir is copied from `/build` directory
2. Add `setup.py` to make `eth2_specs` as a Python module
3. Add `doctest` in CI

### How to setup `docs`
```sh
pip install -e .[dev,docs]

cd docs/; sphinx-build -W -T -E . _build/html
```
Then you can see the entry point would be at
`/docs/_build/html/index.html`. And the main preview page is `/docs/_build/html/core/0_beacon-chain/index.html`.

### Quick tutorial
1. The converted `.rst` file of phase 0 spec: https://github.com/hwwhww/eth2.0-specs/blob/hwwhww/sphinx/docs/core/0_beacon-chain/index.rst
2. I only updated
    - "Informative" section, using `.rst` formatting external links 
    - The helper functions part [here](https://github.com/hwwhww/eth2.0-specs/blob/hwwhww/sphinx/docs/core/0_beacon-chain/index.rst#helper-functions): to mirror the source code of a certain function, we can add:

```
.. literalinclude:: ../../../eth2_specs/phase0/spec.py
   :pyobject: <function_name>
```
#### How does it look like:

image

image

### Pros
- Nicer CI/tests environment: no need for `function_puller.py`!
- Better versioning than a pure markdown file.
- Better ToC and better reading experience.
- No matter what's the output of the CI workflow from #793, IMHO having `eth2_specs` module would make the tests much more natural.

### Cons
- The contributors will feel that they are hacking Python instead of proposing an idea; but also, everyone can open a well-documented doc in issue and Specs Elves can help implement it.
- @protolambda: it may be too far from "specification", it would be more like documentation.
- reStructuredText...

I might be biased, so I wonder what do the contributors and readers think about it?
/cc @protolambda @djrtwo @JustinDrake @vbuterin @pipermerriam

### CODE REVIEW

**Comment by djrtwo** [comment]
I don't expect this is going to get movement until we near a phase 0 spec freeze. Can we close this for now?

**Comment by pipermerriam** [comment]
@hwwhww re-open if you want.  I clicked the button thinking this was the Issue I had opened before realizing it was your PR.

**Comment by hwwhww** [comment]
@djrtwo @pipermerriam sounds good to me :)

**Comment by protolambda** [comment]
On a related note, if we are looking into example-outputs, something like this may be an interesting take to enable people to play with documentation: https://github.com/aaren/notedown
Not really a documentation website however, py-notebooks are more of a local experimentation tool.

**Pull request closed without merging**
