### PR TITLE
Rename shard_block_root -> crosslink_data_root

### PR DESCRIPTION
**Pull request by vbuterin**

### CODE REVIEW

**Comment by JustinDrake** [comment]
Brainstorming: `crosslink_hash`, `crosslink_root`, `crosslink_commitment`, `shard_commitment`

**Comment by vbuterin** [comment]
Or `data_root` or `shard_data_root`.

**Comment by JustinDrake** [comment]
Or `shard_root` or `shard_hash`.

**Comment by vbuterin** [comment]
I like the word "data" in there; it reminds the reader that it has something to do with the data in a shard, as opposed to various other shard-related things (eg. state)

**Comment by JustinDrake** [comment]
I like the word "shard" or "crosslink" in there to differentiate from beacon-related things. What about `crosslink_data_root`?

**Comment by vbuterin** [comment]
Sure :)

**Pull request merged**
