### PR TITLE
Add `syncnets` data to Altair `MetaData`

### LINKED ISSUE #2347: Altair p2p MetaData should contain syncnets field
Currently, the `MetaData` field https://github.com/ethereum/eth2.0-specs/blob/dev/specs/phase0/p2p-interface.md#metadata contains only the `attnets` field to signal a change in the subscribed attestation subnets to our peers. 

We should similarly have the `syncnets` field in `MetaData` so we can signal changes in our subscribed sync committee subnets.

### PR DESCRIPTION
**Pull request by ralexstokes**
Fixes #2347.

### CODE REVIEW

**Comment by pawanjay176** [comment]
This would also add a v2 version for `GetMetaData` response  in rpc right?

**Comment by djrtwo** [comment]
> This would also add a v2 version for `GetMetaData` response in rpc right?

Yes, I think that's the simplest way to handle the content changes on the `MetaData` type here.

**Comment by ralexstokes** [comment]
Added the "get metadata v2" req/resp endpoint -- the guide already discusses upgrading to v2 ahead of the fork so it seems that has already been covered

**Review by djrtwo — APPROVED** [review]
excellent. thank you!

**Pull request merged**
