### PR TITLE
Separate config files by phases + update phase 1 configs

### PR DESCRIPTION
**Pull request by hwwhww**
1. I recalled that @paulhauner once mentioned the current config file for testnet contains too many under-development phase 1 stuff. I do think it would be neater to separate configs. We have 4 files in this PR:
    - minimal_phase0.yaml
    - minimal_phase1.yaml
    - mainnet_phase0.yaml
    - mainnet_phase1.yaml

2. Some phase1 numbers in config files were outdated, this PR also sync with the latest beacon chain spec.

### CODE REVIEW

**Comment by djrtwo** [comment]
What about `configs/{network}/{fork}` (e.g. `configs/mainnet/phase_0`)? I think this will result in a bit easier management

**Comment by hwwhww** [comment]
@djrtwo 
Good idea! Updated them to `configs/{network}/{fork}` format.

Another minor issue you reminded me of is `phase0` v.s. `phase_0`:
- We currently use `phase0` as the fork name in pyspec
https://github.com/ethereum/eth2.0-specs/blob/67c9c062e0f94d4331d1b9fe149eb5254cb34f8c/tests/core/pyspec/eth2spec/test/context.py#L26-L27 and `setup.py`
- We have directory name `eth2.0-specs/specs/phase0`
- We have package `eth2spec.phase0`
- We have directory name: `eth2.0-specs/tests/core/pyspec/eth2spec/test/phase_0`

I'm using `phase0` now because I guess one day we may want to "only use phase 0" config for testing phase 0 tests. IMO it seems easier to rename `eth2.0-specs/tests/core/pyspec/eth2spec/test/phase_0` to `eth2.0-specs/tests/core/pyspec/eth2spec/test/phase0` in a new PR.

**Comment by djrtwo** [comment]
yeah, thought about that too while typing it 😅 
`phase0` works. and we can migrate the testing dir soon

**Comment by djrtwo** [comment]
cc: @protolambda this will modify the testing release instructions

**Pull request merged**
