### PR TITLE
revert e128 and c901 in lint

### PR DESCRIPTION
**Pull request by djrtwo**
Revert removal of E128 and C901. The offending lines had already been resolved so I'd rather keep the restrictions in unless we run into a specific issue we cant' elegantly resolve

### CODE REVIEW

**Comment by dankrad** [comment]
So I now get this:

```
flake8  --ignore=E252,W504,W503 --max-line-length=120 ./eth2spec \
&& cd ./eth2spec && mypy --follow-imports=silent --warn-unused-ignores --ignore-missing-imports --check-untyped-defs --disallow-incomplete-defs --disallow-untyped-defs -p phase0 \
&& mypy --follow-imports=silent --warn-unused-ignores --ignore-missing-imports --check-untyped-defs --disallow-incomplete-defs --disallow-untyped-defs -p phase1;
./eth2spec/debug/random_value.py:38:1: C901 'get_random_ssz_object' is too complex (21)
./eth2spec/debug/encode.py:8:1: C901 'encode' is too complex (12)
./eth2spec/test/utils.py:7:1: C901 'vector_test' is too complex (16)
./eth2spec/test/phase_0/epoch_processing/test_process_justification_and_finalization.py:12:1: C901 'add_mock_attestations' is too complex (11)
Makefile:103: recipe for target 'lint' failed
make: *** [lint] Error 1
```

Why do you not have that problem?

**Comment by hwwhww** [comment]
@dankrad are you using the correct flake8 and mypy versions?
- flake8==3.7.7
- mypy==0.750

Maybe try `make install_test` again.

**Comment by dankrad** [comment]
```
(venv) df@gutenberg:~/slashdata/creative/data/ethereum/eth2.0-specs$ flake8 --version
3.7.7 (mccabe: 0.6.1, pycodestyle: 2.5.0, pyflakes: 2.1.1) CPython 3.8.0 on Linux
(venv) df@gutenberg:~/slashdata/creative/data/ethereum/eth2.0-specs$ mypy --version
mypy 0.750
```

What am I doing wrong?

**Comment by hwwhww** [comment]
Aah, so by https://github.com/ethereum/eth2.0-specs/pull/1902, you added your flake8 config `tox.ini`. What's your local configuration in `tox.ini`?

**Comment by dankrad** [comment]
Ah, that's why -- I had a "max-complexity" line in there. Thanks. I somehow thought that file wouldn't apply for flake8 called from the makefile, only for the visual studio config.

Since that seems to be applied automatically, would it make sense to just have all the flake8 configs in tox.ini? Then the IDEs and the "make lint" command would automatically use the same config.

**Comment by hwwhww** [comment]
Sounds good to me. 👍 

I'm not sure if it's loaded automatically in CI. We can use flag to point to the config file specifically, e.g., `flake8 --config linter.ini` and `mypy --config-file linter.ini`.

https://github.com/ethereum/eth2.0-specs/commit/5bbbf4fe74b9ceaba9bc8b1c8fb3fdf92f38a0ef (of PR #1707) has an example of setting `mypy.ini`. I'll create a new PR for the configuration file setting. :)

**Pull request merged**
