### PR TITLE
Homogenised start shard

### PR DESCRIPTION
**Pull request by JustinDrake**
When the committee count equals `SHARD_COUNT`, add an offset. Fix item 28 in #675.

Screenshot 2019-04-07 at 10 47 39

(Went with a slightly improved approach which still allows for committee count to equal `SHARD_COUNT`.)

### CODE REVIEW

**Comment by djrtwo** [comment]
Not terribly happy about the cleanliness here, but it works.

**Comment by vbuterin** [comment]
This seems far too bulky for the purpose. Why not just:

```
def get_shard_delta(active_validator_count: int) -> int:
    committee_count = get_epoch_committee_count(active_validator_count)
    return min(committee_count, SHARD_COUNT - SHARD_COUNT // EPOCH_LENGTH)
```

Alternatively, we can replace the last line with `return committee_count if committee_count < SHARD_COUNT else SHARD_COUNT // EPOCH_LENGTH` to keep exact functionality.

**Comment by djrtwo** [comment]
Is this what you meant?

**Comment by JustinDrake** [comment]
I'd say `return committee_count if committee_count < SHARD_COUNT else SHARD_COUNT // EPOCH_LENGTH` is better than `min(committee_count, SHARD_COUNT - SHARD_COUNT // EPOCH_LENGTH)`. The reason is that the former allows for all shards to get crosslinked in every epoch whereas the latter always leaves `SHARD_COUNT // EPOCH_LENGTH` shards behind.

**Comment by vbuterin** [comment]
Ah no, I meant not adding any of the other logic in the PR and instead _just_ adding the get_shard_delta function.

**Comment by djrtwo** [comment]
closed in favor of #889

**Pull request closed without merging**
