### PR TITLE
Fair proposer selection probability

### PR DESCRIPTION
**Pull request by vbuterin**
Makes a validator's probability of being selected as a proposer proportional to a validator's balance. This ensures fairness between validators of different deposit sizes, making proposer manipulation attacks more expensive and ensuring that there is no advantage to be gained by concentrating one's ETH in more vs fewer validator slots. This allows us to widen the gap between the min and max deposit size.

Note that as a side effect, proposer selection becomes less predictable, but I don't feel like this is a large downside. Specifically, the proposer selection does not have a guaranteed 1 epoch lookahead like the committees do. This change is noted in the validator guide within this PR.

### CODE REVIEW

**Comment by JustinDrake** [comment]
I refactored the logic to remove the line `return first_committee[epoch % len(first_committee)]` because it would never get triggered in practice (not friendly to testing), and it's also simpler :)

**Comment by vbuterin** [comment]
OK that works. I had thought you might favor a constant bound on runtime, but I suppose the probability of it actually going longer than ~100 rounds is cryptographically securely low in any case.

**Comment by djrtwo** [comment]
Can you write a note to implementers on why this is needed/desirable?

**Comment by djrtwo** [comment]
> Note that as a side effect, proposer selection becomes less predictable, but I don't feel like this is a large downside.

Ah, this means there is no longer a guaranteed 1 epoch lookahead. You can know your committee but don't know if you are the proposer until start of epoch because of potential changes in balance. We need to make note of this in V-guide -- you cannot tell if proposer until epoch-of even if you used lookahead on your committee/slot

**Comment by vbuterin** [comment]
> Can you write a note to implementers on why this is needed/desirable?

Done.

> Ah, this means there is no longer a guaranteed 1 epoch lookahead. You can know your committee but don't know if you are the proposer until start of epoch because of potential changes in balance. We need to make note of this in V-guide -- you cannot tell if proposer until epoch-of even if you used lookahead on your committee/slot

Correct. There's a guaranteed 1-epoch lookahead for which committee you will be in, but not proposer status. Although we expect that ~99.99%+ of the time, the proposer will nevertheless be the same in two different branches, because balances don't change _that_ much.

**Comment by djrtwo** [comment]
Fixed a couple of minor bugs and modified the validator guide to not have lookahead on proposing. Just on committee

**Pull request merged**
