### PR TITLE
Clean up data structures

### PR DESCRIPTION
**Pull request by JustinDrake**
This includes:

* Giving every data structure a name (e.g. `BeaconChainBlock`)
* Making data structure names consistent (e.g. `SpecialObject` => `SpecialRecord`)
* Arranging the fields within the data structures in a more logical/consistent manner
* Reworking the comments to be more concise and to the point
* Rename some fields for consistency:
    * `shard_id` => `shard` (for consistency with `withdrawal_shard`)
    * `last_state_recalculation` => `last_state_recalculation_slot` (for consistency with `last_finalized_slot`, `last_justified_slot`, etc.)
    * `current_dynasty` => `dynasty` (for consistency with `slot`, `shard`)
    * `pow_chain_ref` => `pow_chain_reference` (abbreviations are avoided throughout)
* Various other cleanups

### CODE REVIEW

**Comment by hwwhww** [comment]
Maybe just `BeaconBlock`?

**Comment by djrtwo** [comment]
lgtm.

We need to rename `SpecialRecord.type` as `type` is a built-in in a number of languages.

Thoughts? `variety`, `typ`, `opcode`, `code` are the ones I can come up with

**Comment by djrtwo** [comment]
Right, but most of these implementations will expose these fields as methods or attributes on the instantiated objects.

@arnetheduck recommended `kind` which seems reasonable.

**Comment by JustinDrake** [comment]
@djrtwo Changed to `kind`

**Comment by djrtwo** [comment]
Great. Fixed conflict. merging

**Pull request merged**
