### PR TITLE
Enable Milagro BLS in CI

### PR DESCRIPTION
**Pull request by hwwhww**
This draft PR shows the CI errors in phase 1 tests.

```
FAILED eth2spec/test/phase1/sanity/test_blocks.py::test_with_shard_transition_with_custody_challenge_and_response
FAILED eth2spec/test/phase1/block_processing/test_process_shard_transition.py::test_multiple_offset_slots
FAILED eth2spec/test/phase1/sanity/test_blocks.py::test_custody_slashing - As...
FAILED eth2spec/test/phase1/block_processing/test_process_shard_transition.py::test_basic_crosslinks
FAILED eth2spec/test/phase1/sanity/test_blocks.py::test_process_beacon_block_with_normal_shard_transition
FAILED eth2spec/test/phase1/sanity/test_blocks.py::test_process_beacon_block_with_empty_proposal_transition
```

### CODE REVIEW

**Comment by hwwhww** [comment]
@protolambda using `--bls-type=milagro` doesn't make the CI too slow with minimal config (it takes ~3 to 5 minutes to run the tests). I'd say let's enable it.

**Comment by hwwhww** [comment]
To reviewers: #1990 fixes the CI.

**Comment by djrtwo** [comment]
looks fine, pending #1990

**Review by Supattra0712 — COMMENTED** [review]
เอาที่ไหนก้อไมรุ้

**Pull request merged**
