### PR TITLE
per-epoch Balance difference consensus safety note

### PR DESCRIPTION
**Pull request by djrtwo**
addresses #243

### CODE REVIEW

**Comment by djrtwo** [comment]
eh, I hear you.
I just want to get it in there so it is not forgotten as we do more formal security analysis.

**Comment by djrtwo** [comment]
How about this @JustinDrake?

**Comment by JustinDrake** [comment]
I meant a cleaner solution, not a cleaner presentation 😂. I think it would simplify formal analysis if we didn't have this wrinkle.

**Comment by vbuterin** [comment]
I think wrinkles are unavoidable. The reason is that it's already inevitably going to be the case that if two competing chains get finalized, the validators will have slightly different balances on them due to various rewards and penalties, so the fault tolerance will not be exactly 1/3. If we end up formally proving security, we'll have to use an argument involving bounding the per-epoch change in validator balances in any case.

**Pull request merged**
