### PR TITLE
Add definition for `bytesN` helpers

### PR DESCRIPTION
**Pull request by ralexstokes**
Addresses #101

### CODE REVIEW

**Comment by djrtwo** [comment]
Can you add python typehints for the new function?

**Comment by hwwhww** [comment]
@ralexstokes thanks for making this PR. Do you mind fixing the conflicts?

**Comment by ralexstokes** [comment]
@hwwhww looks like i fixed the conflict.... by pulling in the intervening history. happy to create a new PR that just cherry-picks the relevant commits if you'd like -- the original merge conflict was just w/ the reorg into `spec/core` documents so it will be easy w/ a cherry-pick

**Comment by djrtwo** [comment]
Going to close this PR.

The helper is currently defined on the fly in the spec

```
We define another set of helpers to be used throughout: bytes1(x): return x.to_bytes(1, 'big'), bytes2(x): return x.to_bytes(2, 'big'), and so on for all integers, particularly 1, 2, 3, 4, 8, 32.
```

**Pull request closed without merging**
