### PR TITLE
removes deposit_* prefixes

### PR DESCRIPTION
**Pull request by decanus**
certain objects are already like this, I feel it only makes sense to remove prefixes before `data`

### CODE REVIEW

**Comment by djrtwo** [comment]
Major merge conflict here..

**Comment by decanus** [comment]
@djrtwo Majorly resolved

**Comment by JustinDrake** [comment]
As a heads up I will refactor deposits (see https://github.com/ethereum/eth2.0-specs/issues/760) and take this PR into account.

**Comment by JustinDrake** [comment]
Closing in favour of #780.

**Pull request closed without merging**
