### PR TITLE
Added FixedSizeList wrappers

### PR DESCRIPTION
**Pull request by vbuterin**
Requires corresponding changes to the spec pythonizer.

### CODE REVIEW

**Comment by JustinDrake** [comment]
Should we go with `Arrray`? (It's what Golang uses. Also see [this comment](https://github.com/ethereum/eth2.0-specs/pull/696#discussion_r261393027).)

**Comment by CarlBeek** [comment]
> Should we go with `Arrray`? (It's what Golang uses. Also see [this comment](https://github.com/ethereum/eth2.0-specs/pull/696#discussion_r261393027).)

I disagree with this notation. Many, if not the majority of, languages seem to deem `Array` to be dynamically sized. [[Source](https://en.wikipedia.org/w/index.php?title=Comparison_of_programming_languages_(array)#Array_system_cross-reference_list)]

**Comment by JustinDrake** [comment]
That table is pretty cool. It looks like it's roughly 50/50 (what they call "init" and "heap" is a special case of fixed sized).

**Comment by CarlBeek** [comment]
Agreed. My point is more that the terminology may be ambiguous to users of certain languages. (A quick poll of the 3 CS majors in the room with me had them all declaring it to be dynamic. (I am aware this is not a strong argument))

**Comment by vbuterin** [comment]
If we want clarity, the name needs to evoke the property that actually make static and dynamic sized lists different. List vs tuple, array vs slice, list vs array all fail to do that.

I'll keep thinking for better alternatives...

**Comment by protolambda** [comment]
Ideas: Mutable List vs Immutable list. Or appendable list vs fixed list. Or list vs vector.

Honestly I think it's better to keep it simple and be clear in the definition of the type itself.
Slice vs Array is clear enough for me, and so is List vs Tuple.

**Comment by vbuterin** [comment]
If one-word-ness is a desideratum then list vs vector is definitely the least bad of what I've seen so far.

**Comment by JustinDrake** [comment]
+1 for list vs vector. Happy to rename "tuple" to "vector" in the SSZ spec.

**Pull request merged**
